import { Inter } from 'next/font/google'
import '@/app/globals.css'
import SideMenu from '@/components/SideMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` inter.className flex min-h-screen`}>
        <SideMenu/>
        {children}
      </body>
    </html>
  )
}
